/* eslint-disable @typescript-eslint/no-explicit-any */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 1871_skirt_gurmyzhskaya.glb 
Author: Aleksei Moskvin (https://sketchfab.com/alekseimoskvin1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/1871-skirt-gurmyzhskaya-6f4a6bc2f31d49218ba8af26eccbd431
Title: 1871 Skirt (Gurmyzhskaya)
*/
import { useGLTF } from '@react-three/drei'

const glb = new URL("./1871_skirt_gurmyzhskaya.glb", import.meta.url).href;

export function Skirt(props: any) {
  const { nodes, materials } = useGLTF(glb);
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <mesh geometry={(nodes['18_Skirt_18_Skirt_0'] as any).geometry} material={materials['18_Skirt']} scale={10} />
        <meshStandardMaterial color={(props.color as string) || "red"} />
      </group>
    </group>
  )
}

useGLTF.preload(glb)
