/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 man_pants.glb 
Author: adityajaiswal9968 (https://sketchfab.com/adityajaiswal9968)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/man-pants-e74836a0171045fdbdcf341eecfea892
Title: man pants
*/
import { useGLTF } from '@react-three/drei'

const glb = new URL("./man_pants.glb", import.meta.url).href;

export function Pants(props: any) {
  const { nodes, materials } = useGLTF(glb);
  return (
    <group {...props} dispose={null}>
      <group position={[-2.619, 35.69, 1.75]} rotation={[-Math.PI / 2, 0, 0]} scale={1.038}>
        <mesh
          geometry={(nodes['pants_03_-_Default_0'] as any).geometry}
          material={!props.color ? materials['03_-_Default'] : undefined}
          position={[2.414, 2.357, 15.914]}
          rotation={[0.305, 0, 0]}
        >
          {props.color && <meshStandardMaterial color={(props.color as string)} />}
        </mesh>
      </group>
    </group>
  )
}
