/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 t-shirt_low_poly.glb 
Author: Chirag.Vijay (https://sketchfab.com/Chirag.Vijay)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/t-shirt-low-poly-3e4b13a502884acfbd79cee0f9cd8876
Title: T-Shirt Low Poly
*/
import { useGLTF } from "@react-three/drei";

const glb = new URL("./t-shirt_low_poly.glb", import.meta.url).href;

export function Model(props:any) {
  const { nodes, materials } = useGLTF(glb);
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={(nodes["T-Shirt_Material_0"] as any).geometry}
          material={materials.Material}
          position={[0.878, 1.703, 1.51]}
          scale={2.692}
        >
          <meshStandardMaterial color={(props.color as string) || "red"} />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/t-shirt_low_poly.glb");
