/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 womens_shirt.glb 
Author: Kirll (https://sketchfab.com/milk8982618milk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/womens-shirt-cfe3a4c135424c65825fb07503021f3d
Title: women's shirt
*/
import { useGLTF } from "@react-three/drei";

const glb = new URL("./womens_shirt.glb", import.meta.url).href;

export function WomensShirt(props: any) {
  const { nodes, materials } = useGLTF(glb);
  return (
    <group {...props} dispose={null}>
      <group scale={0.025}>
        <group position={[-12.444, 0, 20.371]}>
          <group position={[12.444, 0, -20.371]} scale={0.312}>
            <mesh
              geometry={
                (
                  nodes[
                    "FO_001_Oversized-sweater_FABRIC_1_FRONT_3915_010_0"
                  ] as any
                ).geometry
              }
              material={
                !props.color
                  ? materials["Oversized-sweater_FABRIC_1_FRONT_3915_010"]
                  : undefined
              }
              position={[-0.35, -138.342, 2.099]}
            >
              {props.color && (
                <meshStandardMaterial
                  color={(props.color as string) || "red"}
                />
              )}
            </mesh>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/womens_shirt.glb");
